---
- name: Verificar LAMP
  hosts: prod
  tasks:
  - name: Verificar Apache
    service: name=apache2 state=started
  - name: Verificar PHP
    service: name=php state=started
  - name: Verificar MySQL
    service: name=mysql state=started

